site_name: Django REST Swagger
repo_url: https://github.com/marcgibbons/django-rest-swagger
repo_name: GitHub
site_description: Swagger UI / OpenAPI Documentation for Django REST Framework
site_author: Marc Gibbons
copyright: 2013-2016  Marc Gibbons
google_analytics: ['UA-80777383-1', 'auto']
pages:
  - Home: 'index.md'
  - Rendering the Schema: 'schema.md'
  - Settings: 'settings.md'
  - UI Customization: 'customization.md'
